db: "postgres://postgres:postgres@localhost/booklover?sslmode=disable"
#optional parameter -> connection string to couchDB
#couchdb: "http://127.0.0.1:5984/"

# timeouts are set in seconds
db_init_timeout: 60
services_init_timeout: 15

api:
  host: localhost
  port: 2490
  dev_mode: true
  enable_cors: true
  api_request_timeout: 60

dev_mode: true
check_auth: false
auto_migrate: true
wait_for_db: true

log:
  app_name: booklover-backend
  level: debug
  add_trace : true
  sentry: ""
  json: false
